app:
    resource: '@AppBundle/Controller/'
    type: annotation

home:
    path: /home
    defaults: { _controller: AppBundle:Post:getHome, _format: html }
    requirements:
    methods:  [GET, POST]

add:
    path: /add
    defaults: { _controller: AppBundle:Post:addPost, _format: html }
    requirements:
        method: POST

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

onePost:
    path:     /post/{idPost}
    defaults: { _controller: AppBundle:Post:addComment, _format: html }
    requirements:
        method: POST

post_like:
    path:     /post/like/{idPost}
    defaults: { _controller: AppBundle:Vote:addLike, _format: html }
    requirements:
        method: POST

post_unlike:
    path:     /post/unlike/{idPost}
    defaults: { _controller: AppBundle:Vote:addDislike, _format: html }
    requirements:
        method: POST


getPostApi:
    path:     /api/post/{idPost}
    defaults: { _controller: AppBundle:Post:getPostApi, _format: html }
    requirements:
        method: GET


getAllPostApi:
    path:     /api/home
    defaults: { _controller: AppBundle:Post:getAllPostApi, _format: html }
    requirements:
        method: GET

addCommentApi:
    path:     /api/post/{idPost}/addComment
    defaults: { _controller: AppBundle:Post:addCommentApi, _format: html }
    requirements:
        method: POST
