AppBundle\Entity\Post:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PostRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        user:
          targetEntity: User
          joinColumn:
            name: user_id
            referencedColumnName: id
    oneToMany:
        comments:
          targetEntity: Comment
          mappedBy: post
          joinColumn :
            name : comment_id
            referencedColumnName : id
        votes:
           targetEntity: Vote
           mappedBy: post
           joinColumn:
               name: vote_id
               referencedColumnName: id
    fields:
        image:
            type: string
            length: 255
        title:
            type: string
            length: 255
        votePlus :
            type : integer
        voteMoins :
            type : integer

    lifecycleCallbacks: {  }
